kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
  namespace: {{ .Release.Namespace }}
stringData:
  cookie: ERLANG_COOKIE
  password: {{ .Values.password }}
  url: amqp://{{ .Values.username }}:{{ .Values.password }}@{{ .Values.loadbalancerservice.name }}
  username: {{ .Values.username }}
type: Opaque
